<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3S0wx6l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3S0wx6l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3S0wx6l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3S0wx6l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3S0wx6l\App_KernelDevDebugContainer([
    'container.build_hash' => '3S0wx6l',
    'container.build_id' => 'bb13df77',
    'container.build_time' => 1680591375,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3S0wx6l');
